[package]
name = "lok2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = 0
opt-level = 3

[dependencies]
to-binary = "*"
structopt = "*"